version: "3"
services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack_test
    ports:
      - "4563-4599:4563-4599"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=dynamodb,lambda,iam
      - DATA_DIR=/tmp/localstack/data
      - AWS_DEFAULT_REGION=us-east-1
      - DEFAULT_REGION=us-east-1
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_DOCKER_NETWORK=sample-lambda_default-network
      - HOSTNAME_EXTERNAL=localstack
    volumes:
      - "./.localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - './localstack_setup:/docker-entrypoint-initaws.d/'
    networks:
      - default-network
networks:
  default-network: